### ISSUE TITLE
about test dice

### ISSUE THREAD

**Issue by ShunXee** [alberto-solano/drive-convmixer#1]
I think the test dice in your paper is not the real test dice. The ground truth of the test in your dataset is missing. Perhaps you place the largest dice in a training session in the article?There is also no mention of testing in the code.

**Comment by alberto-solano** [comment]
Predictions on test images are evaluated using the DRIVE challenge contest platform, which you can find here:

https://drive.grand-challenge.org/

Therefore we do not have access to the ground truth of the test images. This way we avoid any kind of cheating by increasing the DICE by knowing the true labels.

To test the DICE on the test sample, you must register an account and follow the contest instructions:
"The results should be sent in a single zip file containing a PNG binary file with the bin predictions for the corresponding files in the test set. The file names should be [1.png, 2.png, ..., 20.png]. The dice coefficient will be calculated for each image in the test set (only pixels within the mask are taken into account). The ranking is based on the highest average dice coefficient."

Best regards
